import { useState } from "react";
import { ADMIN_PIN, POSITIONS } from "../constants/index";
import { LogoImg } from "../constants/logo";
import { calcAge, gid } from "../lib/utils";
import { IS, LS, OS } from "../ui/styles";

export default function LoginScreen({ profiles, onSelect, onCreate, isMobile, club, onChangeClub }) {
  const [mode, setMode] = useState(profiles.length === 0 ? "create" : "select");
  const [name, setName] = useState(""); const [pos, setPos] = useState("Smaçör"); const [bday, setBday] = useState(""); const [gender, setGender] = useState("erkek"); const [pin, setPin] = useState("");
  const [adminPin, setAdminPin] = useState(""); const [adminErr, setAdminErr] = useState(false);
  const [selId, setSelId] = useState(null); const [pinInput, setPinInput] = useState(""); const [pinErr, setPinErr] = useState(false);
  function handleCreate() { if (!name) return; if (pos === "Antrenör" && adminPin !== ADMIN_PIN) { setAdminErr(true); return; } onCreate({ id: gid(), name, position: pos, birthDate: bday, gender, pin: pin || "" }); }
  function handleSelect() { const p = profiles.find(x => x.id === selId); if (!p) return; if (p.pin && p.pin !== pinInput) { setPinErr(true); return; } onSelect(p); }
  return (
    <div style={{ minHeight: "100vh", background: "#111318", display: "flex", alignItems: "center", justifyContent: "center", fontFamily: "'DM Sans', sans-serif" }}>
      <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800;900&display=swap" rel="stylesheet" />
      <div style={{ width: isMobile ? "90%" : 440, padding: isMobile ? 20 : 40 }}>
        <div style={{ textAlign: "center", marginBottom: 32 }}><div style={{ display: "flex", justifyContent: "center", marginBottom: 8 }}><LogoImg size={80} /></div><h1 style={{ margin: 0, fontSize: 32, fontWeight: 900, color: "#F0F0F0" }}>VOLLEYZ<span style={{ color: "#FF6B35" }}>UP</span></h1><div style={{ fontSize: 12, color: "#4A4F5C", letterSpacing: "0.15em", fontWeight: 600, marginTop: 4 }}>ANTRENMAN TAKİP SİSTEMİ</div></div>
        {club && (
          <div style={{ background: "rgba(255,107,53,0.06)", border: "1px solid rgba(255,107,53,0.2)", borderRadius: 12, padding: "12px 16px", marginBottom: 24, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <div><div style={{ color: "#FF6B35", fontWeight: 800, fontSize: 16 }}>{club.name}</div><div style={{ color: "#4A4F5C", fontSize: 11 }}>Kod: <span style={{ color: "#8A8F98", fontWeight: 700, letterSpacing: "0.1em" }}>{club.code}</span></div></div>
            <button onClick={onChangeClub} style={{ background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 8, padding: "5px 10px", color: "#6B7080", fontSize: 11, cursor: "pointer" }}>Kulüp Değiştir</button>
          </div>
        )}
        {mode === "select" ? (
          <div><h2 style={{ color: "#E0E0E0", fontSize: 18, fontWeight: 700, marginBottom: 16, textAlign: "center" }}>Sporcu Seç</h2>{profiles.map(p => (<div key={p.id} onClick={() => { setSelId(p.id); setPinErr(false); setPinInput(""); }} style={{ background: selId === p.id ? "rgba(255,107,53,0.1)" : "rgba(255,255,255,0.03)", border: `1px solid ${selId === p.id ? "rgba(255,107,53,0.3)" : "rgba(255,255,255,0.06)"}`, borderRadius: 14, padding: "16px 20px", marginBottom: 8, cursor: "pointer", display: "flex", justifyContent: "space-between" }}><div><div style={{ color: "#F0F0F0", fontWeight: 700 }}>{p.name}</div><div style={{ color: "#6B7080", fontSize: 12 }}>{p.position}{p.birthDate ? ` · ${calcAge(p.birthDate)} yaş` : ""}</div></div><div style={{ display: "flex", alignItems: "center", gap: 8 }}>{p.pin && <span style={{ fontSize: 10, color: "#4A4F5C" }}>🔒</span>}{selId === p.id && <span style={{ color: "#FF6B35", fontSize: 20 }}>→</span>}</div></div>))}{selId && profiles.find(x => x.id === selId)?.pin && (<div style={{ marginTop: 12 }}><label style={LS}>PIN</label><input style={IS} type="password" maxLength={4} placeholder="4 haneli PIN" value={pinInput} onChange={e => { setPinInput(e.target.value); setPinErr(false); }} />{pinErr && <div style={{ color: "#FF6B6B", fontSize: 12, marginTop: 4 }}>Hatalı PIN</div>}</div>)}{selId && <button onClick={handleSelect} style={{ background: "linear-gradient(135deg, #FF6B35, #FF8C5A)", border: "none", borderRadius: 12, padding: "14px 0", color: "#fff", fontWeight: 800, fontSize: 16, cursor: "pointer", width: "100%", marginTop: 16 }}>Giriş Yap</button>}<div style={{ textAlign: "center", marginTop: 20 }}><button onClick={() => setMode("create")} style={{ background: "none", border: "none", color: "#6B7080", fontSize: 13, cursor: "pointer", textDecoration: "underline" }}>+ Yeni Sporcu Oluştur</button></div><div style={{ textAlign: "center", marginTop: 8 }}><button onClick={onChangeClub} style={{ background: "none", border: "none", color: "#4A4F5C", fontSize: 12, cursor: "pointer", textDecoration: "underline" }}>Farklı kulüple giriş yap</button></div></div>
        ) : (
          <div><h2 style={{ color: "#E0E0E0", fontSize: 18, fontWeight: 700, marginBottom: 16, textAlign: "center" }}>Profil Oluştur</h2><div style={{ marginBottom: 14 }}><label style={LS}>İsim *</label><input style={IS} value={name} onChange={e => setName(e.target.value)} placeholder="Ad Soyad" /></div><div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr", gap: 12, marginBottom: 14 }}><div><label style={LS}>Pozisyon</label><select style={IS} value={pos} onChange={e => setPos(e.target.value)}>{POSITIONS.map(p => <option key={p} style={OS}>{p}</option>)}</select></div><div><label style={LS}>Cinsiyet</label><select style={IS} value={gender} onChange={e => setGender(e.target.value)}><option value="erkek" style={OS}>Erkek</option><option value="kadın" style={OS}>Kadın</option></select></div></div>{pos === "Antrenör" && (<div style={{ marginBottom: 14, background: "rgba(255,80,80,0.05)", padding: 12, borderRadius: 10, border: "1px solid rgba(255,80,80,0.2)" }}><label style={{...LS, color: "#FF6B6B"}}>Kulüp Güvenlik Şifresi *</label><input style={{...IS, borderColor: adminErr ? "#FF6B6B" : undefined}} type="password" value={adminPin} onChange={e => { setAdminPin(e.target.value); setAdminErr(false); }} />{adminErr && <div style={{ color: "#FF6B6B", fontSize: 12, marginTop: 4 }}>Hatalı şifre!</div>}</div>)}<div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr", gap: 12, marginBottom: 14 }}><div><label style={LS}>Doğum Tarihi</label><input style={IS} type="date" value={bday} onChange={e => setBday(e.target.value)} /></div><div><label style={LS}>PIN (opsiyonel)</label><input style={IS} type="password" maxLength={4} placeholder="4 hane" value={pin} onChange={e => setPin(e.target.value.replace(/\D/g, ""))} /></div></div><button onClick={handleCreate} disabled={!name} style={{ background: name ? "linear-gradient(135deg, #FF6B35, #FF8C5A)" : "#333", border: "none", borderRadius: 12, padding: "14px 0", color: "#fff", fontWeight: 800, fontSize: 16, cursor: name ? "pointer" : "not-allowed", width: "100%", opacity: name ? 1 : 0.5 }}>Oluştur & Giriş Yap</button>{profiles.length > 0 && <div style={{ textAlign: "center", marginTop: 16 }}><button onClick={() => setMode("select")} style={{ background: "none", border: "none", color: "#6B7080", fontSize: 13, cursor: "pointer", textDecoration: "underline" }}>← Sporcu Seçimine Dön</button></div>}<div style={{ textAlign: "center", marginTop: 8 }}><button onClick={onChangeClub} style={{ background: "none", border: "none", color: "#4A4F5C", fontSize: 12, cursor: "pointer", textDecoration: "underline" }}>Farklı kulüple giriş yap</button></div></div>
        )}
      </div>
    </div>
  );
}

