

export const EXERCISE_LIBRARY = [
  // ═══ PLİOMETRİ ═══
  { name: "Squat Jump", category: "plyometric", level: "temel", defSets: 3, defReps: "8", desc: "İki ayakla squat pozisyonundan dikey sıçrama", videoLink: "https://www.youtube.com/results?search_query=squat+jump+tutorial" },
  { name: "Broad Jump", category: "plyometric", level: "temel", defSets: 3, defReps: "8", desc: "Yerinde durarak ileri sıçrama", videoLink: "https://www.youtube.com/results?search_query=broad+jump+technique" },
  { name: "Lateral Hop", category: "plyometric", level: "temel", defSets: 3, defReps: "8/taraf", desc: "Tek bacak yan sıçramalar", videoLink: "https://www.youtube.com/results?search_query=lateral+hop+exercise" },
  { name: "Ankle Hop", category: "plyometric", level: "temel", defSets: 3, defReps: "15", desc: "Ayak bileği ile sürekli küçük sıçramalar", videoLink: "https://www.youtube.com/results?search_query=ankle+hops+plyometric" },
  { name: "Çuval Atlama", category: "plyometric", level: "temel", defSets: 3, defReps: "10", desc: "İki ayakla basit sıçrama (8-11 yaş)", videoLink: "https://www.youtube.com/results?search_query=two+foot+jump+kids+exercise" },
  { name: "Box Jump", category: "plyometric", level: "orta", defSets: 4, defReps: "6", desc: "Kutuya sıçrama, kontrollü iniş", videoLink: "https://www.youtube.com/results?search_query=box+jump+proper+form" },
  { name: "Single-Leg Jump", category: "plyometric", level: "orta", defSets: 3, defReps: "6/bacak", desc: "Tek bacak dikey sıçrama", videoLink: "https://www.youtube.com/results?search_query=single+leg+vertical+jump" },
  { name: "Approach Jump", category: "plyometric", level: "orta", defSets: 4, defReps: "6", desc: "Smaç koşusu ile sıçrama", videoLink: "https://www.youtube.com/results?search_query=volleyball+approach+jump+tutorial" },
  { name: "Tuck Jump", category: "plyometric", level: "orta", defSets: 3, defReps: "8", desc: "Sıçrayarak dizleri göğüse çekme", videoLink: "https://www.youtube.com/results?search_query=tuck+jump+exercise" },
  { name: "Lateral Bound", category: "plyometric", level: "orta", defSets: 3, defReps: "8/taraf", desc: "Geniş adımla yan sıçrama", videoLink: "https://www.youtube.com/results?search_query=lateral+bound+plyometric" },
  { name: "Box Step-Up", category: "plyometric", level: "orta", defSets: 3, defReps: "10", desc: "Kutuya çıkma (20-30cm)", videoLink: "https://www.youtube.com/results?search_query=box+step+up+exercise" },
  { name: "Depth Jump", category: "plyometric", level: "ileri", defSets: 4, defReps: "5", desc: "Kutudan düşüp reaktif sıçrama. Temas <200ms", videoLink: "https://www.youtube.com/results?search_query=depth+jump+volleyball" },
  { name: "Reactive Jump", category: "plyometric", level: "ileri", defSets: 4, defReps: "5", desc: "Ardışık reaktif sıçramalar", videoLink: "https://www.youtube.com/results?search_query=reactive+jump+training" },
  { name: "Hurdle Jump Series", category: "plyometric", level: "ileri", defSets: 3, defReps: "6", desc: "Engel üzeri ardışık sıçramalar", videoLink: "https://www.youtube.com/results?search_query=hurdle+jump+series+plyometric" },
  { name: "Plyometric Push-Up", category: "plyometric", level: "ileri", defSets: 3, defReps: "8", desc: "Patlayıcı şınav", videoLink: "https://www.youtube.com/results?search_query=plyometric+push+up" },
  { name: "Reactive Bounding", category: "plyometric", level: "ileri", defSets: 3, defReps: "8", desc: "Uzun adımlarla sıçrama serisi", videoLink: "https://www.youtube.com/results?search_query=reactive+bounding+drill" },
  { name: "Drop Jump (RSI)", category: "plyometric", level: "ileri", defSets: 4, defReps: "5", desc: "RSI geliştirme. Hedef: >2.5 E, >1.8 K", videoLink: "https://www.youtube.com/results?search_query=drop+jump+RSI+protocol" },
  { name: "Ağırlıklı Yelek Sıçrama", category: "plyometric", level: "ileri", defSets: 3, defReps: "6", desc: "%5-10 VA yelek ile sıçrama", videoLink: "https://www.youtube.com/results?search_query=weighted+vest+jump+training" },
  { name: "Band Destekli Sıçrama", category: "plyometric", level: "ileri", defSets: 3, defReps: "6", desc: "Direnç bandı ile sıçrama", videoLink: "https://www.youtube.com/results?search_query=band+assisted+jump+training" },

  // ═══ KUVVET ═══
  { name: "Back Squat", category: "strength", level: "orta", defSets: 4, defReps: "5-8", desc: "%70-80 1RM. Hedef: ≥2× VA", videoLink: "https://www.youtube.com/results?search_query=back+squat+proper+form" },
  { name: "Front Squat", category: "strength", level: "orta", defSets: 4, defReps: "5-8", desc: "Ön squat, quad dominant", videoLink: "https://www.youtube.com/results?search_query=front+squat+technique" },
  { name: "Goblet Squat", category: "strength", level: "temel", defSets: 3, defReps: "12", desc: "Hafif kettlebell ile squat", videoLink: "https://www.youtube.com/results?search_query=goblet+squat+tutorial" },
  { name: "Bulgarian Split Squat", category: "strength", level: "orta", defSets: 3, defReps: "10/bacak", desc: "Tek bacak split squat", videoLink: "https://www.youtube.com/results?search_query=bulgarian+split+squat" },
  { name: "Romanian Deadlift", category: "strength", level: "orta", defSets: 4, defReps: "8", desc: "Hamstring & gluteus", videoLink: "https://www.youtube.com/results?search_query=romanian+deadlift+form" },
  { name: "Single-Leg RDL", category: "strength", level: "temel", defSets: 3, defReps: "10/bacak", desc: "Denge + kalça aktivasyonu", videoLink: "https://www.youtube.com/results?search_query=single+leg+rdl+tutorial" },
  { name: "Glute Bridge", category: "strength", level: "temel", defSets: 3, defReps: "15", desc: "Kalça aktivasyonu", videoLink: "https://www.youtube.com/results?search_query=glute+bridge+exercise" },
  { name: "Hip Thrust", category: "strength", level: "orta", defSets: 4, defReps: "10", desc: "Ağırlıklı kalça kaldırma", videoLink: "https://www.youtube.com/results?search_query=barbell+hip+thrust" },
  { name: "Leg Press", category: "strength", level: "orta", defSets: 4, defReps: "10", desc: "Makine ile bacak presi", videoLink: "https://www.youtube.com/results?search_query=leg+press+form" },
  { name: "Calf Raise", category: "strength", level: "temel", defSets: 4, defReps: "15", desc: "Baldır güçlendirme", videoLink: "https://www.youtube.com/results?search_query=calf+raise+exercise" },
  { name: "Bench Press", category: "strength", level: "orta", defSets: 4, defReps: "6-8", desc: "Üst gövde itme gücü", videoLink: "https://www.youtube.com/results?search_query=bench+press+proper+form" },
  { name: "Push Press", category: "strength", level: "orta", defSets: 4, defReps: "5", desc: "Bacak destekli overhead. Hedef: ≥1× VA", videoLink: "https://www.youtube.com/results?search_query=push+press+technique" },
  { name: "Overhead Press", category: "strength", level: "orta", defSets: 4, defReps: "8", desc: "Omuz güç dayanıklılığı", videoLink: "https://www.youtube.com/results?search_query=overhead+press+tutorial" },
  { name: "Barbell Row", category: "strength", level: "orta", defSets: 4, defReps: "8", desc: "Sırt & latissimus", videoLink: "https://www.youtube.com/results?search_query=barbell+row+form" },
  { name: "Weighted Pull-Up", category: "strength", level: "ileri", defSets: 4, defReps: "5", desc: "Ağırlıklı barfiks", videoLink: "https://www.youtube.com/results?search_query=weighted+pull+up" },
  { name: "Push-Up", category: "strength", level: "temel", defSets: 3, defReps: "15", desc: "Temel itme hareketi", videoLink: "https://www.youtube.com/results?search_query=push+up+proper+form" },
  { name: "Pull-Up", category: "strength", level: "temel", defSets: 3, defReps: "max", desc: "Temel çekme hareketi", videoLink: "https://www.youtube.com/results?search_query=pull+up+tutorial+beginner" },
  { name: "Dip", category: "strength", level: "temel", defSets: 3, defReps: "10", desc: "Paralel bar dips", videoLink: "https://www.youtube.com/results?search_query=parallel+bar+dips" },
  { name: "Lat Pulldown", category: "strength", level: "temel", defSets: 3, defReps: "12", desc: "Lat çekme, sırt genişliği", videoLink: "https://www.youtube.com/results?search_query=lat+pulldown+form" },
  { name: "Dumbbell Shoulder Press", category: "strength", level: "temel", defSets: 3, defReps: "10", desc: "Dumbbell omuz presi", videoLink: "https://www.youtube.com/results?search_query=dumbbell+shoulder+press" },
  { name: "Lunges", category: "strength", level: "temel", defSets: 3, defReps: "12/bacak", desc: "Yürüyüş veya yerinde lunge", videoLink: "https://www.youtube.com/results?search_query=walking+lunges+form" },

  // ═══ OLİMPİK KALDIRIŞ ═══
  { name: "Hang Clean", category: "olympic", level: "orta", defSets: 4, defReps: "4", desc: "Hız-kuvvet gelişimi", videoLink: "https://www.youtube.com/results?search_query=hang+clean+tutorial" },
  { name: "Power Clean", category: "olympic", level: "ileri", defSets: 4, defReps: "3", desc: "Yerden tam temiz kaldırış", videoLink: "https://www.youtube.com/results?search_query=power+clean+technique" },
  { name: "Kettlebell Swing", category: "olympic", level: "temel", defSets: 3, defReps: "15", desc: "Kalça ekstansiyon gücü", videoLink: "https://www.youtube.com/results?search_query=kettlebell+swing+form" },
  { name: "French Contrast Method", category: "olympic", level: "ileri", defSets: 3, defReps: "4", desc: "Ağır + plyo + hafif + plyo", videoLink: "https://www.youtube.com/results?search_query=french+contrast+method+volleyball" },
  { name: "Hang Snatch", category: "olympic", level: "ileri", defSets: 4, defReps: "3", desc: "Askı koparma — omuz mobilitesi + patlayıcılık", videoLink: "https://www.youtube.com/results?search_query=hang+snatch+tutorial" },
  { name: "Clean & Jerk", category: "olympic", level: "ileri", defSets: 4, defReps: "2", desc: "Tam olimpik kaldırış", videoLink: "https://www.youtube.com/results?search_query=clean+and+jerk+technique" },
  { name: "Dumbbell Snatch", category: "olympic", level: "orta", defSets: 3, defReps: "6/taraf", desc: "Tek kol dumbbell koparma", videoLink: "https://www.youtube.com/results?search_query=dumbbell+snatch+tutorial" },
  { name: "Trap Bar Deadlift", category: "olympic", level: "orta", defSets: 4, defReps: "5", desc: "Hex bar deadlift — güç temeli", videoLink: "https://www.youtube.com/results?search_query=trap+bar+deadlift+form" },

  // ═══ HIZ & ÇEVİKLİK ═══
  { name: "10-20m Sprint", category: "speed", level: "temel", defSets: 6, defReps: "1", defDuration: "maks", desc: "Kısa mesafe ivmelenme", videoLink: "https://www.youtube.com/results?search_query=short+sprint+training+technique" },
  { name: "5-10-5 Shuttle", category: "speed", level: "orta", defSets: 6, defReps: "1", desc: "Yön değiştirme (COD)", videoLink: "https://www.youtube.com/results?search_query=5+10+5+shuttle+drill" },
  { name: "T-Drill", category: "speed", level: "orta", defSets: 5, defReps: "1", desc: "Hedef: <9.5sn E, <10.5sn K", videoLink: "https://www.youtube.com/results?search_query=t+drill+agility+test" },
  { name: "Pro Agility", category: "speed", level: "orta", defSets: 5, defReps: "1", desc: "Çeviklik testi ve antrenmanı", videoLink: "https://www.youtube.com/results?search_query=pro+agility+drill" },
  { name: "Illinois Agility", category: "speed", level: "orta", defSets: 4, defReps: "1", desc: "Uzun mesafe çeviklik parkuru", videoLink: "https://www.youtube.com/results?search_query=illinois+agility+test" },
  { name: "Lateral Shuffle 4×5m", category: "speed", level: "orta", defSets: 5, defReps: "1", desc: "Yan kayma. Hedef: <5.0sn", videoLink: "https://www.youtube.com/results?search_query=lateral+shuffle+drill+volleyball" },
  { name: "Reaktif Agility", category: "speed", level: "ileri", defSets: 6, defReps: "1", desc: "Koni/ışık sinyaline tepki", videoLink: "https://www.youtube.com/results?search_query=reactive+agility+drill" },
  { name: "Libero Savunma Deseni", category: "speed", level: "ileri", defSets: 4, defReps: "1", defDuration: "30sn", desc: "Voleybol özel savunma desenleri", videoLink: "https://www.youtube.com/results?search_query=volleyball+libero+defense+drill" },
  { name: "Merdiven Çalışması", category: "speed", level: "temel", defSets: 3, defReps: "2 tur", defDuration: "20dk", desc: "Koordinasyon merdiveni", videoLink: "https://www.youtube.com/results?search_query=agility+ladder+drills" },
  { name: "Koni Çalışması", category: "speed", level: "temel", defSets: 3, defReps: "3 tur", desc: "Çember/koni koordinasyon", videoLink: "https://www.youtube.com/results?search_query=cone+drill+agility" },
  { name: "Tepki Egzersizi (Renkli Koni)", category: "speed", level: "orta", defSets: 5, defReps: "1", defDuration: "30sn", desc: "Tepki hızı geliştirme", videoLink: "https://www.youtube.com/results?search_query=reaction+cone+drill" },
  { name: "ATP-PCr Sprint (6sn)", category: "speed", level: "ileri", defSets: 8, defReps: "1", defDuration: "6sn+3dk din.", desc: "6sn maksimal sprint, 3dk dinlenme", videoLink: "https://www.youtube.com/results?search_query=ATP+PCr+sprint+training" },
  { name: "Backpedal to Sprint", category: "speed", level: "orta", defSets: 6, defReps: "1", desc: "Geri koşudan öne sprint geçişi", videoLink: "https://www.youtube.com/results?search_query=backpedal+to+sprint+drill" },

  // ═══ MOBİLİTE & ESNEKLİK ═══
  { name: "Wall Ankle Mobilization", category: "mobility", level: "temel", defSets: 3, defReps: "15/taraf", desc: "Dorsifleksiyon ≥35° hedef", videoLink: "https://www.youtube.com/results?search_query=wall+ankle+mobilization" },
  { name: "90/90 Hip Stretch", category: "mobility", level: "temel", defSets: 2, defReps: "60sn/taraf", desc: "Kalça fleksiyon ≥120°", videoLink: "https://www.youtube.com/results?search_query=90+90+hip+stretch" },
  { name: "Hip Flexor Stretch", category: "mobility", level: "temel", defSets: 2, defReps: "45sn/taraf", desc: "Kalça fleksör germe", videoLink: "https://www.youtube.com/results?search_query=hip+flexor+stretch" },
  { name: "Thread-the-Needle", category: "mobility", level: "temel", defSets: 2, defReps: "10/taraf", desc: "Torakal rotasyon ≥45°/taraf", videoLink: "https://www.youtube.com/results?search_query=thread+the+needle+stretch" },
  { name: "Thoracic Spine Mob.", category: "mobility", level: "temel", defSets: 2, defReps: "10/taraf", desc: "Göğüs omurgası hareketliliği", videoLink: "https://www.youtube.com/results?search_query=thoracic+spine+mobilization" },
  { name: "Sleeper Stretch", category: "mobility", level: "temel", defSets: 2, defReps: "45sn/taraf", desc: "Omuz İR+ER = ≥180° hedef", videoLink: "https://www.youtube.com/results?search_query=sleeper+stretch+shoulder" },
  { name: "GIRD Protokolü", category: "mobility", level: "orta", defSets: 3, defReps: "10/taraf", desc: "Omuz internal rotasyon eksikliği", videoLink: "https://www.youtube.com/results?search_query=GIRD+shoulder+protocol" },
  { name: "Omuz Kapsül Germe", category: "mobility", level: "temel", defSets: 2, defReps: "30sn/taraf", desc: "Omuz genel hareketliliği", videoLink: "https://www.youtube.com/results?search_query=shoulder+capsule+stretch" },
  { name: "Dinamik Esneme", category: "mobility", level: "temel", defSets: 1, defReps: "1", defDuration: "10dk", desc: "Isınma öncesi dinamik esneme", videoLink: "https://www.youtube.com/results?search_query=dynamic+stretching+warm+up" },
  { name: "Foam Rolling (Üst Sırt)", category: "mobility", level: "temel", defSets: 1, defReps: "1", defDuration: "3dk", desc: "Torakal bölge foam roller", videoLink: "https://www.youtube.com/results?search_query=foam+rolling+upper+back" },
  { name: "Foam Rolling (Quadriceps)", category: "mobility", level: "temel", defSets: 1, defReps: "1", defDuration: "2dk/taraf", desc: "Ön bacak foam roller", videoLink: "https://www.youtube.com/results?search_query=foam+roll+quads" },
  { name: "Pigeon Stretch", category: "mobility", level: "orta", defSets: 2, defReps: "45sn/taraf", desc: "Derin kalça esnekliği", videoLink: "https://www.youtube.com/results?search_query=pigeon+stretch+hip" },
  { name: "Cat-Cow", category: "mobility", level: "temel", defSets: 2, defReps: "10", desc: "Omurga mobilizasyonu", videoLink: "https://www.youtube.com/results?search_query=cat+cow+exercise" },

  // ═══ CORE ═══
  { name: "Plank", category: "core", level: "temel", defSets: 3, defReps: "1", defDuration: "45sn", desc: "Temel core stabilizasyonu", videoLink: "https://www.youtube.com/results?search_query=plank+proper+form" },
  { name: "Dead Bug", category: "core", level: "temel", defSets: 3, defReps: "10/taraf", desc: "Anti-extension core", videoLink: "https://www.youtube.com/results?search_query=dead+bug+exercise" },
  { name: "Bird-Dog", category: "core", level: "temel", defSets: 3, defReps: "10/taraf", desc: "Core stabilizasyonu + koordinasyon", videoLink: "https://www.youtube.com/results?search_query=bird+dog+exercise" },
  { name: "Side Plank", category: "core", level: "temel", defSets: 3, defReps: "1", defDuration: "30sn/taraf", desc: "McGill Big 3 — lateral", videoLink: "https://www.youtube.com/results?search_query=side+plank+exercise" },
  { name: "McGill Curl-Up", category: "core", level: "temel", defSets: 3, defReps: "10", desc: "McGill Big 3 — ön core", videoLink: "https://www.youtube.com/results?search_query=mcgill+curl+up" },
  { name: "Pallof Press", category: "core", level: "orta", defSets: 3, defReps: "10/taraf", desc: "Anti-rotasyon core", videoLink: "https://www.youtube.com/results?search_query=pallof+press+exercise" },
  { name: "Russian Twist", category: "core", level: "orta", defSets: 3, defReps: "20", desc: "Rotasyonel core gücü", videoLink: "https://www.youtube.com/results?search_query=russian+twist+exercise" },
  { name: "Ab Wheel Rollout", category: "core", level: "ileri", defSets: 3, defReps: "8", desc: "İleri düzey anti-extension", videoLink: "https://www.youtube.com/results?search_query=ab+wheel+rollout" },
  { name: "Hanging Leg Raise", category: "core", level: "ileri", defSets: 3, defReps: "10", desc: "Barda asılı bacak kaldırma", videoLink: "https://www.youtube.com/results?search_query=hanging+leg+raise" },
  { name: "Medicine Ball Slam", category: "core", level: "orta", defSets: 3, defReps: "12", desc: "Patlayıcı core + üst gövde", videoLink: "https://www.youtube.com/results?search_query=medicine+ball+slam" },
  { name: "Woodchop (Kablo)", category: "core", level: "orta", defSets: 3, defReps: "10/taraf", desc: "Rotasyonel güç, smaç transferi", videoLink: "https://www.youtube.com/results?search_query=cable+woodchop+exercise" },

  // ═══ YARALANMA ÖNLEME ═══
  { name: "Nordic Hamstring Curl", category: "injury_prev", level: "orta", defSets: 3, defReps: "6", desc: "Hamstring ekzantrik güç", videoLink: "https://www.youtube.com/results?search_query=nordic+hamstring+curl" },
  { name: "VMO Aktivasyonu", category: "injury_prev", level: "temel", defSets: 3, defReps: "15", desc: "Patellar tendon koruması", videoLink: "https://www.youtube.com/results?search_query=VMO+activation+exercise" },
  { name: "Thrower's Ten", category: "injury_prev", level: "orta", defSets: 2, defReps: "15", desc: "Omuz koruma programı", videoLink: "https://www.youtube.com/results?search_query=throwers+ten+program" },
  { name: "Rotator Cuff Yükleme", category: "injury_prev", level: "temel", defSets: 3, defReps: "15/taraf", desc: "İR/ER band çalışması", videoLink: "https://www.youtube.com/results?search_query=rotator+cuff+band+exercise" },
  { name: "Propriosepsiyon", category: "injury_prev", level: "temel", defSets: 3, defReps: "30sn/taraf", desc: "Tek bacak denge, wobble board", videoLink: "https://www.youtube.com/results?search_query=proprioception+balance+training" },
  { name: "Peroneal Güçlendirme", category: "injury_prev", level: "temel", defSets: 3, defReps: "15", desc: "Ayak bileği dış kas grubu", videoLink: "https://www.youtube.com/results?search_query=peroneal+strengthening+exercise" },
  { name: "Ekzantrik Yükleme", category: "injury_prev", level: "orta", defSets: 3, defReps: "12", desc: "Tendon sağlığı protokolü", videoLink: "https://www.youtube.com/results?search_query=eccentric+loading+tendon" },
  { name: "Scapular Push-Up", category: "injury_prev", level: "temel", defSets: 3, defReps: "12", desc: "Skapula stabilizasyonu", videoLink: "https://www.youtube.com/results?search_query=scapular+push+up" },
  { name: "Band Pull-Apart", category: "injury_prev", level: "temel", defSets: 3, defReps: "15", desc: "Arka omuz & skapula", videoLink: "https://www.youtube.com/results?search_query=band+pull+apart+exercise" },
  { name: "Ayak Bileği Bandı (4 yön)", category: "injury_prev", level: "temel", defSets: 2, defReps: "15/yön", desc: "Dorsi/plantar/inversyon/eversyon", videoLink: "https://www.youtube.com/results?search_query=ankle+band+4+way+exercise" },

  // ═══ KONDİSYON ═══
  { name: "Glikolitik Interval", category: "conditioning", level: "orta", defSets: 6, defReps: "1", defDuration: "30sn+90sn", desc: "30sn yüksek yoğunluk", videoLink: "https://www.youtube.com/results?search_query=glycolytic+interval+training" },
  { name: "Aerobik Taban Koşusu", category: "conditioning", level: "temel", defSets: 1, defReps: "1", defDuration: "20-30dk", desc: "Haftada 1-2 orta tempo", videoLink: "https://www.youtube.com/results?search_query=aerobic+base+running" },
  { name: "Su İçinde Kondisyon", category: "conditioning", level: "temel", defSets: 1, defReps: "1", defDuration: "30dk", desc: "Eklem dostu kondisyon", videoLink: "https://www.youtube.com/results?search_query=pool+conditioning+workout" },
  { name: "Cross-Training", category: "conditioning", level: "temel", defSets: 1, defReps: "1", defDuration: "30-45dk", desc: "Yüzme/bisiklet, aktif toparlanma", videoLink: "https://www.youtube.com/results?search_query=cross+training+for+athletes" },
  { name: "Tabata Protokolü", category: "conditioning", level: "ileri", defSets: 8, defReps: "1", defDuration: "20sn iş+10sn din.", desc: "4 dk yüksek yoğunluk interval", videoLink: "https://www.youtube.com/results?search_query=tabata+workout+protocol" },
  { name: "Fartlek Koşusu", category: "conditioning", level: "orta", defSets: 1, defReps: "1", defDuration: "20dk", desc: "Değişken tempolu koşu", videoLink: "https://www.youtube.com/results?search_query=fartlek+running" },
  { name: "Bisiklet Ergometresi", category: "conditioning", level: "temel", defSets: 1, defReps: "1", defDuration: "20dk", desc: "Düşük etkili kardiyovasküler", videoLink: "https://www.youtube.com/results?search_query=bike+ergometer+workout" },
  { name: "Kürek Ergometresi", category: "conditioning", level: "orta", defSets: 1, defReps: "1", defDuration: "2000m", desc: "Tüm vücut kondisyon", videoLink: "https://www.youtube.com/results?search_query=rowing+ergometer+workout" },

  // ═══ VOLEYBOL TEKNİK ═══
  { name: "Top Koordinasyonu", category: "volleyball", level: "temel", defSets: 1, defReps: "1", defDuration: "15dk", desc: "Balon/hafif top becerisi", videoLink: "https://www.youtube.com/results?search_query=volleyball+ball+handling+drills" },
  { name: "Smaç Koşusu Tekniği", category: "volleyball", level: "orta", defSets: 4, defReps: "8", desc: "Approach jump teknik", videoLink: "https://www.youtube.com/results?search_query=volleyball+spike+approach+technique" },
  { name: "Blok Tekniği", category: "volleyball", level: "orta", defSets: 4, defReps: "8", desc: "Blok zamanlaması ve hareket", videoLink: "https://www.youtube.com/results?search_query=volleyball+blocking+technique" },
  { name: "Servis Çalışması", category: "volleyball", level: "temel", defSets: 3, defReps: "10", desc: "Float / jump serve", videoLink: "https://www.youtube.com/results?search_query=volleyball+serve+technique+tutorial" },
  { name: "Savunma Drilleri", category: "volleyball", level: "orta", defSets: 4, defReps: "1", defDuration: "3dk", desc: "Savunma refleksi ve pozisyon", videoLink: "https://www.youtube.com/results?search_query=volleyball+defense+drills" },
  { name: "Parmak Pas Tekniği", category: "volleyball", level: "temel", defSets: 3, defReps: "20", desc: "Setting — parmak pas temeli", videoLink: "https://www.youtube.com/results?search_query=volleyball+setting+technique" },
  { name: "Manşet Pas Tekniği", category: "volleyball", level: "temel", defSets: 3, defReps: "20", desc: "Bump pass temeli", videoLink: "https://www.youtube.com/results?search_query=volleyball+bump+pass+technique" },
  { name: "Jump Serve (Smaç Servis)", category: "volleyball", level: "ileri", defSets: 3, defReps: "10", desc: "Smaç servis tekniği", videoLink: "https://www.youtube.com/results?search_query=volleyball+jump+serve+tutorial" },
  { name: "Çapraz Smaç", category: "volleyball", level: "orta", defSets: 4, defReps: "8", desc: "Çapraz vuruş tekniği", videoLink: "https://www.youtube.com/results?search_query=volleyball+cross+court+spike" },
  { name: "Smaç Kol Mekaniği", category: "volleyball", level: "orta", defSets: 3, defReps: "15", desc: "Doğru kol salınımı ve bilek snabı", videoLink: "https://www.youtube.com/results?search_query=volleyball+arm+swing+mechanics" },
  { name: "Setter Dump / Tip", category: "volleyball", level: "ileri", defSets: 3, defReps: "10", desc: "Pasör atak çeşitleri", videoLink: "https://www.youtube.com/results?search_query=volleyball+setter+dump+tip" },
  { name: "Pipe Atak", category: "volleyball", level: "ileri", defSets: 4, defReps: "6", desc: "Arka bölge atak (pipe)", videoLink: "https://www.youtube.com/results?search_query=volleyball+pipe+attack" },
  { name: "Serve Receive (Karşılama)", category: "volleyball", level: "orta", defSets: 4, defReps: "1", defDuration: "5dk", desc: "Servis karşılama pozisyonu", videoLink: "https://www.youtube.com/results?search_query=volleyball+serve+receive+drill" },

  // ═══ TAKTİK & SİSTEM ═══
  { name: "5-1 Sistem Rotasyonları", category: "taktik", level: "orta", defSets: 1, defReps: "1", defDuration: "20dk", desc: "Pasör kaçma ve oyuncu dizilişleri", videoLink: "https://www.youtube.com/results?search_query=volleyball+5-1+rotation+explained" },
  { name: "6-2 Sistem Çalışması", category: "taktik", level: "orta", defSets: 1, defReps: "1", defDuration: "20dk", desc: "Çift pasör sistemi rotasyonları", videoLink: "https://www.youtube.com/results?search_query=volleyball+6-2+system+rotation" },
  { name: "Hücum Kombinasyonları", category: "taktik", level: "ileri", defSets: 1, defReps: "1", defDuration: "25dk", desc: "Quick, slide, pipe, back row atak", videoLink: "https://www.youtube.com/results?search_query=volleyball+offensive+combinations" },
  { name: "Blok Sistemleri (Bunch/Spread)", category: "taktik", level: "ileri", defSets: 1, defReps: "1", defDuration: "20dk", desc: "Blok stratejileri ve geçişler", videoLink: "https://www.youtube.com/results?search_query=volleyball+blocking+system+bunch+spread" },
  { name: "Savunma Dizilişleri", category: "taktik", level: "orta", defSets: 1, defReps: "1", defDuration: "20dk", desc: "Perimeter vs rotation defense", videoLink: "https://www.youtube.com/results?search_query=volleyball+defense+formation+rotation" },
  { name: "Transition Oyunu", category: "taktik", level: "ileri", defSets: 1, defReps: "1", defDuration: "20dk", desc: "Savunmadan hücuma geçiş", videoLink: "https://www.youtube.com/results?search_query=volleyball+transition+offense" },
  { name: "Oyun Analizi (Video)", category: "taktik", level: "orta", defSets: 1, defReps: "1", defDuration: "30dk", desc: "Rakip video analizi, kendi maç analizi", videoLink: "https://www.youtube.com/results?search_query=volleyball+game+analysis+how+to" },
  { name: "Set Arası Taktik Konuşma", category: "taktik", level: "temel", defSets: 1, defReps: "1", defDuration: "5dk", desc: "Huddle & set arası iletişim drilli", videoLink: "https://www.youtube.com/results?search_query=volleyball+team+communication+drill" },

  // ═══ MENTAL ODAK ═══
  { name: "Box Breathing (Nefes)", category: "mental", level: "temel", defSets: 1, defReps: "1", defDuration: "5dk", desc: "4-4-4-4 nefes odaklanma tekniği", videoLink: "https://www.youtube.com/results?search_query=box+breathing+technique+athletes" },
  { name: "Görselleştirme (Visualization)", category: "mental", level: "temel", defSets: 1, defReps: "1", defDuration: "10dk", desc: "Smaç/servis/savunma zihinsel prova", videoLink: "https://www.youtube.com/results?search_query=visualization+technique+athletes" },
  { name: "Pozitif Self-Talk Drilli", category: "mental", level: "temel", defSets: 1, defReps: "1", defDuration: "5dk", desc: "Hata sonrası toparlanma cümleleri", videoLink: "https://www.youtube.com/results?search_query=positive+self+talk+sports+psychology" },
  { name: "Pre-Performance Rutini", category: "mental", level: "orta", defSets: 1, defReps: "1", defDuration: "3dk", desc: "Servis/smaç öncesi mental hazırlık", videoLink: "https://www.youtube.com/results?search_query=pre+performance+routine+volleyball" },
  { name: "Mindfulness Meditasyonu", category: "mental", level: "temel", defSets: 1, defReps: "1", defDuration: "10dk", desc: "Farkındalık meditasyonu", videoLink: "https://www.youtube.com/results?search_query=mindfulness+meditation+for+athletes" },
  { name: "Odak Yenileme Tekniği", category: "mental", level: "orta", defSets: 1, defReps: "1", defDuration: "2dk", desc: "Oyun içi dikkat dağılmasına karşı", videoLink: "https://www.youtube.com/results?search_query=refocus+technique+sports" },
  { name: "Takım İletişimi Drilli", category: "mental", level: "temel", defSets: 1, defReps: "1", defDuration: "10dk", desc: "Call-out, coverage iletişimi", videoLink: "https://www.youtube.com/results?search_query=volleyball+team+communication+drill" },
  { name: "Baskı Altında Performans", category: "mental", level: "ileri", defSets: 1, defReps: "1", defDuration: "15dk", desc: "Simülasyon: son set, deuce senaryoları", videoLink: "https://www.youtube.com/results?search_query=pressure+training+volleyball" },
];

