import { useState } from "react";
import { EXERCISE_LIBRARY } from "../constants/exercises";
import { CATEGORIES, LEVEL_COLORS, LEVEL_LABELS } from "../constants/index";
import { BTN, IS } from "../ui/styles";

export default function LibraryPage({ isMobile }) {
  const [fc, setFc] = useState("all"); const [fl, setFl] = useState("all"); const [q, setQ] = useState("");
  const filtered = EXERCISE_LIBRARY.filter(ex => (fc === "all" || ex.category === fc) && (fl === "all" || ex.level === fl) && (!q || ex.name.toLowerCase().includes(q.toLowerCase()) || ex.desc.toLowerCase().includes(q.toLowerCase())));
  const grouped = {}; filtered.forEach(ex => { if (!grouped[ex.category]) grouped[ex.category] = []; grouped[ex.category].push(ex); });
  return (<div><h2 style={{ fontSize: 28, fontWeight: 800, color: "#F0F0F0", margin: "0 0 8px" }}>Egzersiz Kütüphanesi</h2><p style={{ color: "#6B7080", fontSize: 14, marginBottom: 16 }}>{EXERCISE_LIBRARY.length} egzersiz · {CATEGORIES.length} kategori</p><input style={{ ...IS, marginBottom: 16, maxWidth: 400 }} placeholder="Egzersiz ara..." value={q} onChange={e => setQ(e.target.value)} /><div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 8 }}><button onClick={() => setFc("all")} style={BTN(fc === "all")}>Tümü</button>{CATEGORIES.map(c => <button key={c.id} onClick={() => setFc(c.id)} style={BTN(fc === c.id, c.color)}>{c.icon} {c.label}</button>)}</div><div style={{ display: "flex", gap: 6, flexWrap: "wrap", marginBottom: 24 }}>{["all", "temel", "orta", "ileri"].map(l => <button key={l} onClick={() => setFl(l)} style={BTN(fl === l, l === "all" ? "#F0F0F0" : LEVEL_COLORS[l])}>{l === "all" ? "Tüm Seviyeler" : LEVEL_LABELS[l]}</button>)}</div>{Object.keys(grouped).length === 0 ? <p style={{ color: "#4A4F5C" }}>Bulunamadı</p> : Object.entries(grouped).map(([catId, exs]) => { const cat = CATEGORIES.find(c => c.id === catId); return (<div key={catId} style={{ marginBottom: 28 }}><h3 style={{ fontSize: 14, color: cat?.color, margin: "0 0 12px", display: "flex", alignItems: "center", gap: 8 }}>{cat?.icon} {cat?.label?.toUpperCase()} <span style={{ color: "#4A4F5C" }}>({exs.length})</span></h3>{exs.map((ex, i) => (<div key={i} style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.05)", borderRadius: 12, padding: 14, marginBottom: 6, borderLeft: `3px solid ${cat?.color}`, display: "flex", flexDirection: isMobile ? "column" : "row", justifyContent: "space-between", gap: 8 }}><div><div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 4, flexWrap: "wrap" }}><span style={{ color: "#F0F0F0", fontWeight: 600 }}>{ex.name}</span><span style={{ background: `${LEVEL_COLORS[ex.level]}18`, color: LEVEL_COLORS[ex.level], padding: "2px 8px", fontSize: 10, borderRadius: 6, fontWeight: 700 }}>{LEVEL_LABELS[ex.level]}</span></div><div style={{ color: "#6B7080", fontSize: 12 }}>{ex.desc}</div>{ex.defSets && <div style={{ color: "#4A4F5C", fontSize: 11, marginTop: 4 }}>{ex.defSets}×{ex.defReps}{ex.defDuration ? ` · ${ex.defDuration}` : ""}</div>}</div><div style={{ display: "flex", gap: 8, alignItems: "center", flexShrink: 0 }}>{ex.videoLink && <a href={ex.videoLink} target="_blank" rel="noreferrer" style={{ background: "rgba(255,107,53,0.15)", color: "#FF6B35", padding: "4px 12px", borderRadius: 6, fontSize: 11, textDecoration: "none", fontWeight: 700, whiteSpace: "nowrap" }}>▶ İzle</a>}</div></div>))}</div>); })}</div>);
}

/* ════════ ANTRENMAN (TAM — KÜTÜPHANELİ EGZERSİZ EKLEME + DÜZENLENEBİLİR) ════════ */
